connMaxIdle: 10 # 通用配置，连接池最大空闲连接数
connMaxOpen: 100 # 通用配置，连接池最大连接数
connMaxLifetime: 1h # 通用配置，连接数最大生命周期
protocol: tcp # 通用配置，传输协议
loc: Local # 通用配置，时区

default:
    driver: mysql # 连接驱动
    dsn: "" # dsn，如果设置了dsn, 以下的所有设置都不生效
    host: localhost # ip地址
    port: 3306 # 端口
    database: coredemo # 数据库
    username: root # 用户名
    password: "localdb001" # 密码
    charset: utf8mb4 # 字符集
    collation: utf8mb4_unicode_ci # 字符序
    timeout: 10s # 连接超时
    readTimeout: 2s # 读超时
    writeTimeout: 2s # 写超时
    parseTime: true # 是否解析时间
    protocol: tcp # 传输协议
    loc: Local # 时区
    connMaxIdle: 10 # 连接池最大空闲连接数
    connMaxOpen: 20 # 连接池最大连接数
    connMaxLifetime: 1h # 连接数最大生命周期

read:
    driver: mysql # 连接驱动
    dsn: "" # dsn，如果设置了dsn, 以下的所有设置都不生效
    host: localhost # ip地址
    port: 3306 # 端口
    database: coredemo # 数据库
    username: root # 用户名
    password: "localdb001" # 密码
    charset: utf8mb4 # 字符集
    collation: utf8mb4_unicode_ci # 字符序